language: python

stages:
  - test
  - coverage
  - deploy

install:
  - pip install -r requirements-dev.txt
script:
  - make test-coverage

jobs:
  include:
    # test
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8-dev
    - python: nightly

    # coverage
    - stage: coverage
      python: 3.8
      install:
        - pip install -r requirements-dev.txt
        - pip install coveralls
      after_success:
        - coveralls

    # deploy
    - stage: deploy
      script:
        - echo "TEST"